-- ============================================================
-- NTUTEC Platform — Migration 012: Update Logo/Photo Local Paths
-- ============================================================
-- Date: 2026-04-14
-- Purpose: After `scripts/download_historical_logos.py` and
--          `scripts/download_wp_images.py` save images into
--          public/historical, public/mentors/wp, public/partners/wp,
--          update DB rows with local paths so the frontend can serve
--          them even after legacy WP goes offline.
-- Depends on: 011 (historical_startups seeded), 009 (mentors seeded)
-- ============================================================

BEGIN;

-- historical_startups.logo_local_path  (361 rows)
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_玉醫科技有限公司_憂鬱症療效預測系統_logo-Shina-Yang.png' WHERE year = '2018' AND name = '憂鬱症療效預測系統 玉醫科技有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_石灣科技有限公司_GOBOT積木小車_logo-Shina-Yang.png' WHERE year = '2018' AND name = '石灣科技有限公司 GOBOT積木小車';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_好好投資科技股份有限公司-Shina-Yang.png' WHERE year = '2018' AND name = '好好投資智能理財平台';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_艾比索_艾比索-閱寫社群平台_logo-Shina-Yang.png' WHERE year = '2018' AND name = '艾比索 EP 插圖日記';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_沂動行銷_SOOCKER熟客定期購平台_logo-Shina-Yang.png' WHERE year = '2018' AND name = '沂動行銷 Soocker 搜客';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_良路設計_走走家具_logo-Shina-Yang.png' WHERE year = '2018' AND name = '良路設計 走走家具';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_貝克生醫_食道癌近接治療置放器_logo-Shina-Yang.png' WHERE year = '2018' AND name = '食道癌近接治療置放器 貝克生醫';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_居家整聊室_生活職人平台_logo-Shina-Yang.png' WHERE year = '2018' AND name = '生活職人平台 居家整聊室';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_KeylessOK_LOGO.png' WHERE year = '2018' AND name = '智慧資產空間管家 客來喜';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_施睿股份有限公司_施睿健康科技-智能血液透析_logo-Shina-Yang.png' WHERE year = '2018' AND name = '施睿健康科技 - 智能血液透析';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_食秘_食秘-餐飲智能採購秘書_logo原foodmap-02-Shina-Yang.png' WHERE year = '2018' AND name = '食秘 餐飲智能採購秘書';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_旅型Travostyle_旅型網站_logo-Shina-Yang.png' WHERE year = '2018' AND name = 'Travostyle 旅型';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_健康盟國際創新有限公司_衛教影音共享平台_logo-Shina-Yang.png' WHERE year = '2018' AND name = '健康盟國際創新有限公司 智能衛教影音共享平台';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_康立安智能醫療設備有限公司_KneeSup_logo-Shina-Yang.png' WHERE year = '2018' AND name = '康立安智能醫療設備有限公司 KneeSup';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_康立安智能醫療設備有限公司_KneeSup_logo-Shina-Yang-1.png' WHERE year = '2018' AND name = '創新非侵入式中央靜脈血氧飽和濃度儀 Innovative and noninvasive central venous oximetry';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_提蜜歐_愛情堅果與Timeo-VR_logo-Shina-Yang.png' WHERE year = '2018' AND name = '緹蜜歐科技 Lovenuts 愛情堅果 & 創新智財開發與分析';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_黑洞科技_雪莉單車_logo-Shina-Yang.png' WHERE year = '2018' AND name = '黑洞科技';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_賈伯利數位科技股份有限公司_Blay_logo-Shina-Yang.png' WHERE year = '2018' AND name = '賈伯利數位科技股份有限公司 Blay';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_跨思科技股份有限公司_書窩_logo-Shina-Yang.png' WHERE year = '2018' AND name = '跨思科技股份有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_漸強實驗室-Crescendo-Lab_BotManager-_logo-Shina-Yang.png' WHERE year = '2018' AND name = 'Crescendo Lab 漸強實驗室';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_睿濱科技_放射治療獨立劑量驗證服務_logo-Shina-Yang.png' WHERE year = '2018' AND name = '睿濱科技';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_維諾股份有限公司_安心_logo-Shina-Yang.png' WHERE year = '2018' AND name = '維諾股份有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_髮弄資訊股份有限公司_STYLEMAP-你的時尚地圖_logo-Shina-Yang.png' WHERE year = '2018' AND name = '髮弄資訊股份有限公司 STYLEMAP';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_謀客股份有限公司_Sligrid_logo-Shina-Yang.png' WHERE year = '2018' AND name = '謀客股份有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_轉帳幫_P2P國際匯款代付_logo-Shina-Yang.png' WHERE year = '2018' AND name = '轉帳幫';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_魔幻主義有限公司_魔法科學班_logo-Shina-Yang-scaled.jpg' WHERE year = '2018' AND name = '魔幻主義有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_Binflux-沛智生醫_Infans-生殖中心智慧管理平台_logo-Shina-Yang.png' WHERE year = '2018' AND name = 'Binflux 沛智生醫';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_Bznk.com_Bznk必可票貼_logo-Shina-Yang.jpg' WHERE year = '2018' AND name = 'Bznk';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_ChaseWind_ChaseWind-Cycling-Glasses_logo-Shina-Yang.png' WHERE year = '2018' AND name = 'ChaseWind';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_Commuter_線上單車-IKEA_logo-Shina-Yang.png' WHERE year = '2018' AND name = 'Commuter';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_Firmso-行旅科技股份有限公司_Frismo_logo-Shina-Yang.png' WHERE year = '2018' AND name = '行旅科技股份有限公司 Firmso';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_FlipWeb-數位資產仲介_數位資產仲介_logo-Shina-Yang.png' WHERE year = '2018' AND name = '數位資產仲介 FlipWeb';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_GoodJob_GoodJob找到你的好頭路-透明求職平台_logo-Shina-Yang.png' WHERE year = '2018' AND name = '幹得好科技股份有限公司 GJ即時上工';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_H.E.R.O._H.E.R.O._logo-Shina-Yang.png' WHERE year = '2018' AND name = 'H.E.R.O.';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_RedString_RedString_logo-Shina-Yang.png' WHERE year = '2018' AND name = 'RedString';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_Teafolks_歐亞茶人國際股份有限公司_茶葉跨國b2b交易平台_logo-Shina-Yang.png' WHERE year = '2018' AND name = '歐亞茶人國際股份有限公司 Teafolks';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_Virtual-Man_Virtual-Man_logo-Shina-Yang.png' WHERE year = '2018' AND name = 'Virtual Man';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_Werold_Going-Down_logo-Shina-Yang.png' WHERE year = '2018' AND name = 'Werold';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_2019_台大車庫_岩寬生醫-Jin-Tang-Chen-Shina-Yang.png' WHERE year = '2018' AND name = '岩寬生醫';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_OM_LOGO-Tanmoy-Kundu-Shina-Yang.png' WHERE year = '2018' AND name = 'OM Charge Sharing';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_吃貨大數據_The-eater_logo-Shina-Yang.png' WHERE year = '2018' AND name = '吃貨大數據 The eater';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_五甫科技股份有限公司_Wolf-Engine_logo-Shina-Yang.png' WHERE year = '2018' AND name = '五甫科技股份有限公司 Wolf Engine';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_智能掛號通_智能掛號通_logo-Shina-Yang.png' WHERE year = '2018' AND name = '智能掛號通';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_樂福袋_樂福袋_logo-Shina-Yang.png' WHERE year = '2018' AND name = '樂福袋';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_KidsExplorer_易智寶_logo-Shina-Yang.png' WHERE year = '2018' AND name = '易智寶 KidsExplorer';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_Meowshroom_循環貓砂_logo-Shina-Yang.png' WHERE year = '2018' AND name = 'meowshroom';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_MirLab_S3_-全方位音樂娛樂學習平台_logo-Shina-Yang.png' WHERE year = '2018' AND name = 'MIRLAB';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_PAMO_3分鐘線上和解服務_logo-Shina-Yang.png' WHERE year = '2018' AND name = 'PAMO';
UPDATE historical_startups SET logo_local_path = '/historical/2018/13624_t-Tumor-Marker-t-條碼客-Steven-Wang-Shina-Yang.jpg' WHERE year = '2018' AND name = 't-條碼客 t-Tumor Marker';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_Aemass.png' WHERE year = '2019' AND name = 'Aemass台灣分部 3D影像製作及分析';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_萌醫寵物科技_LOGO.png' WHERE year = '2019' AND name = '萌醫寵物科技 VELP寵物遠距醫療平台';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_tournii途你logo-Sean-Hsieh-Shina-Yang.png' WHERE year = '2019' AND name = '自遊智載股份有限公司 tournii途你機車租賃平台';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_玉山銀行_LeadBest-logo-Sophy-Yeh-Shina-Yang.png' WHERE year = '2019' AND name = 'LeadBest Consulting Group (原LeadBest)';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_baypay-logo.png' WHERE year = '2019' AND name = '雲飛傳媒有限公司 BayPay灣支付 (原Bytepay)';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_友達_CLOUDMED_單色LOGO-Hung-Chih-Lin-Shina-Yang.png' WHERE year = '2019' AND name = '云醫智能股份有限公司 / CloudMed iCARE 八合一健康管理器';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_KeylessOK_LOGO.png' WHERE year = '2019' AND name = '芝麻開門有限公司 客來喜 飯店智能客服';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_友達光電_台大創創logo-Hannie-Liu-Shina-Yang.png' WHERE year = '2019' AND name = '選優科技有限公司 SHOWHUE';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_17fit.png' WHERE year = '2019' AND name = '老虎網路科技股份有限公司 17FIT';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_東方線上_台大創創logo-VOISS-inc-Shina-Yang.png' WHERE year = '2019' AND name = 'VOISS';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_東方線上_James-Wu-Shina-Yang.png' WHERE year = '2019' AND name = '深智科技股份有限公司 NexRetail';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_頭皮醫生_LOGO.png' WHERE year = '2019' AND name = '量身訂做頭皮管理長照服務 頭皮醫生';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_東方線上_有戲數位logo-Ariel-Lin-Shina-Yang.png' WHERE year = '2019' AND name = '有戲數位股份有限公司 有戲數位 AI Copywriting Platform';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_Logo橫式方底-e1579247832829.png' WHERE year = '2019' AND name = '擴思科技股份有限公司 YoMuscle';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_添翼音樂_Muro-Box-logo-Shiao-Chen-Tsai.png' WHERE year = '2019' AND name = '酷鳩科技有限公司 Muro Box 智慧音樂盒';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_添翼音樂_dwavelogo-Henry-Lin林智源-Shina-Yang.png' WHERE year = '2019' AND name = 'DeepWave迪威智能';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_添翼音樂_slimtab-林季伯-Shina-Yang.png' WHERE year = '2019' AND name = '駭音科技有限公司 SLiMTAB';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_台大車庫_pikabu_logo-Olivia-Su-Shina-Yang.png' WHERE year = '2019' AND name = 'Pikabu 皮卡布';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_台大車庫_衣服圖書館-洪于捷-Shina-Yang.png' WHERE year = '2019' AND name = '線上共享衣櫃 衣服圖書館';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_BumBum.png' WHERE year = '2019' AND name = '透識科技 BumBum';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_台大車庫_岩寬生醫-Jin-Tang-Chen-Shina-Yang.png' WHERE year = '2019' AND name = '溫和抗敏修護及私密處專利保養抑菌醫療級產品 岩寬生醫';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_台大車庫_區塊識集Blockore-Shina-Yang.png' WHERE year = '2019' AND name = '區塊識集 blockore';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_車庫_Hikingbook_logo-柯政祥-Shina-Yang.png' WHERE year = '2019' AND name = 'Hikingbook 登山書股份有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_維諾股份有限公司_安心_logo-Shina-Yang.png' WHERE year = '2019' AND name = '維諾股份有限公司 安心+ 全天候主動式體溫監測預警系';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_樂齡智-logo-PS-yeh-sanyeh.png' WHERE year = '2019' AND name = '樂齡智遊戲 復能樂齡遊戲';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_memorenceAI_logo-e1610694855990.png' WHERE year = '2019' AND name = '智能影像辨識系統 Memorence AI';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_SparKlean_logo-戴文.png' WHERE year = '2019' AND name = '智慧洗衣 到府收送 SparKlean Laundry';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_添翼音樂_富盈數據_玩藝星球logo-Ryan-Huang.png' WHERE year = '2019' AND name = 'ArtzyPlanet 玩藝星球';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_良路設計_走走家具_logo-Shina-Yang.png' WHERE year = '2019' AND name = '良路設計有限公司 走走家具';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_BotBonnie.png' WHERE year = '2019' AND name = '邦妮科技 BotBonnie 對話互動式行銷解決方案';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_雜學青_CodingBar團隊logo-李宗毓.png' WHERE year = '2019' AND name = 'airabbi 瑞比智慧科技 CodingBar';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_小人小學_LOGO.png' WHERE year = '2019' AND name = '籿苗創學文化股份有限公司 / 小人小學 扣扣老師 - 學齡前家庭陪伴IP';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_6.課外通.png' WHERE year = '2019' AND name = '艾貝比科技股份有限公司 課外通';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_LUDO_LOGO.png' WHERE year = '2019' AND name = 'Ludo 人工智能助教';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_發票特務logo_標誌去背-1-e1591084228264.png' WHERE year = '2019' AND name = '樂飛科技股份有限公司 發票特務 INVOICEMAN';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_MoBagel-Logo_BlueYellow.png' WHERE year = '2019' AND name = 'MoBagel Inc. Decanter AI';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_Hunger_LOGO.png' WHERE year = '2019' AND name = '我方策略股份有限公司 Hunger夯客';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_天氣探長logo-Shina-Yang.png' WHERE year = '2019' AND name = '智慧型農務管理系統 天氣探長';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_遠傳_wordup_logo-Shina-Yang.png' WHERE year = '2019' AND name = 'WORD UP';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_遠傳_3drens_Logo_black_white-Shina-Yang.png' WHERE year = '2019' AND name = '車聯網行動定位數據平台 3drens';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_遠傳_domi-logo2019-Shina-Yang.png' WHERE year = '2019' AND name = 'Project Aurora DOMI Earth';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_車庫_DappPocketlogo-Anderson-Chen1-Shina-Yang.png' WHERE year = '2019' AND name = 'Dapp Pocket';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_SIFA_LOGO.png' WHERE year = '2019' AND name = 'SIFA / 視遠科技 SIFA-洗髮精選擇的智慧幫手';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_車庫_Meteo團隊logo-蔡佳昱-Shina-Yang.png' WHERE year = '2019' AND name = 'Meteo團隊 Meteo遊戲式教學電子琴';
UPDATE historical_startups SET logo_local_path = '/historical/2019/13606_2019_車庫_Meteo團隊logo-蔡佳昱-Shina-Yang-1.png' WHERE year = '2019' AND name = '源典智慧醫療服務平台 源典大數據';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_WechatIMG757-William-Chiang.png' WHERE year = '2020' AND name = 'Screea';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_LOGO-反白8cm-拷貝-張智凱.png' WHERE year = '2020' AND name = 'OH!Bot Line@一站式電商服務';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_kryptogologo.png' WHERE year = '2020' AND name = 'KryptoGO GoTrace區塊鏈與加密貨幣分析平台';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_alphalogo.png' WHERE year = '2020' AND name = 'ALPHA Camp';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_surreal-edu-logo-徐凡Joanna.png' WHERE year = '2020' AND name = 'Surreal Education';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2019_雜學校_SAT-logo-衛星知識.png' WHERE year = '2020' AND name = 'SAT. Knowledge SAT. Knowledge Platform';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_Turing-Certs-Logo-Big-胡耀傑.png' WHERE year = '2020' AND name = '圖靈鏈 圖靈證書 TuringCerts';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_logo-1024-翁子騏.png' WHERE year = '2020' AND name = '方格子 方格子 vocus';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2019_友達_Avalanche-Computing_logo-Jay-chen.png' WHERE year = '2020' AND name = 'Avalanche Computing Hyper-Scale Computing';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2019_友達光電＆添翼音樂_Dataxlogo-Aric-Fung.png' WHERE year = '2020' AND name = 'Datax';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_萊司珥得logo-蔡小孟.png' WHERE year = '2020' AND name = '萊司珥得股份有限公司 光盾技術 - 新世代科技淨化整合產品 ( LED/玻璃/光學膜 )';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_pulxionlogo.png' WHERE year = '2020' AND name = '台大機械Pulxion新創團隊 快速評估腦中風及心血管疾病之影像技術';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_PT-LOGO_1024-02-Jarron-蛙哥-Cho-scaled.jpg' WHERE year = '2020' AND name = '深義分析 Retail Insight +';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_drrpinsightlogo.png' WHERE year = '2020' AND name = '深義分析 Retail Insight +';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_streamlogo.png' WHERE year = '2020' AND name = '環球睿視 Ubestream AIchatin';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_numberslogo.png' WHERE year = '2020' AND name = 'Numbers 分散式數據溯源分析系統(Traceable Data Framework: Transparent and Decentralized Analysis System)';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_jjlogo.png' WHERE year = '2020' AND name = 'DT42 DLBox & DL Edge Platform';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_PackAge-配客嘉股份有限公司-logo.png' WHERE year = '2020' AND name = 'PackAge+ 配客嘉股份有限公司 網購包裝循環系統';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_SS運動女孩-logo.jpg' WHERE year = '2020' AND name = 'S&S 運動女孩';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2019_台大車庫_團隊YouLink-logo-Henry-Fan-e1610693494876.png' WHERE year = '2020' AND name = 'YouLink';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_BumBum.png' WHERE year = '2020' AND name = '透識科技 BumBum';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_aurismart智能耳聰.png' WHERE year = '2020' AND name = '智能耳聰 Aurismart AIoT智慧安全輔具';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2020_台大車庫_創創顏值最高-e1610694347341.png' WHERE year = '2020' AND name = '創創顏值最高戰隊 EsScent EsScent 訂閱制香水';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_AmazingTalker（企業page）.png' WHERE year = '2020' AND name = 'AmazingTalker';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_79968b1b-logo_type4_b.png' WHERE year = '2020' AND name = 'VoiceTube 看影片學英語';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_Snapask-logo-color-transparent.png.png' WHERE year = '2020' AND name = 'Snapask時課問';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_49671210_229384961318806_1671608766321131520_n.png' WHERE year = '2020' AND name = 'Qbi益智磁吸軌道玩具 塊樂方程式 Qbi Globe';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_66932081_497007667725206_3295956386826944512_n.png' WHERE year = '2020' AND name = 'MEandMine Body/MEandMine Emotion/MEandMine Theraplay MEandMine';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_logo-1.png' WHERE year = '2020' AND name = 'Glossika';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_1_-5j6988_EttYIBnsdaH2xg.png' WHERE year = '2020' AND name = 'Coding Ocean 海霸 程式老爹';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_logo-mini-4cb1638c1e88eec3b7b90140fd3fa6573937b92bbf864ca849c62c53f2e085bb.png' WHERE year = '2020' AND name = '兒童程式教育完整解決方案 橘子蘋果兒童程式學苑';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_1415543673-707946928.jpg' WHERE year = '2020' AND name = '綿羊犬百寶箱 綿羊犬';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_otojazdqeipi7m5w2ggq.png' WHERE year = '2020' AND name = '語文和程式編輯教育的全功能型機器人 - Kebbi Air 女媧創造';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_下載.png' WHERE year = '2020' AND name = 'STEAM 教育型無人機 Arklab 飛行學院';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2021_親子天下_猿創力程式設計學校Logo-Kennan-Chen-1-1.png' WHERE year = '2020' AND name = '程式設計教育 猿創力程式設計學校';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_fb4cdae3e87487948b22d58b8d0bcdda.png' WHERE year = '2020' AND name = 'Surreal Education SHADOWORKS';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_vt8atds0aoejajkga7n3.png' WHERE year = '2020' AND name = '「MAKAR」AR/VR開放式平台 Mind & Idea Fly Co., Ltd.';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_1453d5e6c8c56df37d231542a9fa901e-330x330-1.jpg' WHERE year = '2020' AND name = 'FlipRobot STEAM Education Solution Actura翻轉機器人團隊';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_大頭照.png' WHERE year = '2020' AND name = '玩轉教學推廣計畫 玩轉學校';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_logo_whitebg_small.07d146dc.fill-640x640-c100.jpg' WHERE year = '2020' AND name = 'STEAM魔法科學課程 菁英魔法學院';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_veyond-1.png' WHERE year = '2020' AND name = '必揚VR學院 VOLLEGE 虛擬實境理化實驗室 必揚實境科技 VEYOND Reality';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_logo-4.jpg' WHERE year = '2020' AND name = '一站式醫療到宅服務平台 牙驛通—牙醫到府居家醫療服務（益康生醫股份有限公司）';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_Logo_橫_中英彩-zoe-liang.png' WHERE year = '2020' AND name = '虛擬健檢、復健系統 龍骨王股份有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_LOGO2.jpg' WHERE year = '2020' AND name = '內容提供/服務整合 愛長照';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2021_台大創創加速器_ApplatoLogo-Yen-Chen.png' WHERE year = '2020' AND name = 'Applato - intelligent healthy dietary solution Applato';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_part_1342_994320_05178.png' WHERE year = '2020' AND name = 'AI線上運動助教 LUDO 如荼科技股份有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_20200531拍片自造所logo去背-影音創客-領客創意.png' WHERE year = '2020' AND name = '拍片自造所';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_jjlogo.png' WHERE year = '2020' AND name = 'DL BOX & DL Platform 灼灼科技';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_健康盟_LOGO標準字中英-王文利-1-1.png' WHERE year = '2020' AND name = '衛教影音共享平台 健康盟';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_logo-2.png' WHERE year = '2020' AND name = 'Encore 專屬熟女的興趣社交平台';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_271156_B.jpg' WHERE year = '2020' AND name = 'LTPA智慧認知訓練方案 樂齡智造科技股份有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2020_UDN聯合報_WaCare遠距健康logo-Terry-Hsieh.png' WHERE year = '2020' AND name = 'WaCare遠距健康';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2020_車庫_gadgethi_台大創創logo-ck1031052王重程.png' WHERE year = '2020' AND name = '自動化產品服務 gadgetHi';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_impct-logo.png' WHERE year = '2020' AND name = '影響貿易 恩沛國際投資';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2020_車庫_水滴logo-Cheng-Jason.png' WHERE year = '2020' AND name = '水滴發票 水滴';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_cropped-a-2.png' WHERE year = '2020' AND name = 'Contal 素養科學班 Contal 教育';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_original.png' WHERE year = '2020' AND name = '客製化年節禮盒、囍餅彌月、點心伴手禮、義大利麵、手搖飲料、義大利麵調理包 Tribake樂芽';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2019_台大車庫_BioMetaSpec-logo-W-M.png' WHERE year = '2020' AND name = 'PlasmaFluo BioMetaSpec';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2019_車庫_優時間銀行雲logo-CJ-Lin.png' WHERE year = '2020' AND name = '優時間銀行雲';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2020_車庫_棗子科技logo-張復龍.png' WHERE year = '2020' AND name = 'TEFCORD排齦線 棗子科技';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_output-onlinepngtools-4-廖佑銘.png' WHERE year = '2020' AND name = '推倒學術付費高牆 Researchain';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_0.jpeg' WHERE year = '2020' AND name = 'Rogy 360度全景攝錄影直播相機 達標智源科技股份有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2568414_original.jpg' WHERE year = '2020' AND name = 'KOLpass';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_9cf7bfe2819254a6117163564537ba434d6c50daf3855e4a7c57129cd22022beae1f7c49a25568f893e5ebfd7ccde3cf180d0fb66964401a8248ab12029be959.jpg' WHERE year = '2020' AND name = 'FOLLOW 數位音訊導覽服務 ＆ Ctrl A 現場-現場營運POS與人流分析系統 揚揚創新科技有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2020_台商資源國際_台大創創logo-luk-wingsan.png' WHERE year = '2020' AND name = 'Count++ Luk Advisor';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_1594894913201-YUCHI-CHI.png' WHERE year = '2020' AND name = 'SLAM GO';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2020台大創創_台商國際_邁摩科技-removebg-Sam-Yen.png' WHERE year = '2020' AND name = '新零售方案 邁摩科技';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2020_春池加速器_CKOY_logo-Jerry-Hsu.png' WHERE year = '2020' AND name = 'Zero CKOY';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_淺色底使用藍logo-Alice.png' WHERE year = '2020' AND name = '無耗材過濾技術 點點塑';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_下載-3.png' WHERE year = '2020' AND name = 'OPO Stack AI智慧電管家';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_noemore_logo-li-Weil.png' WHERE year = '2020' AND name = 'One more 再一杯工作室';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_好盒器LOGO_1024-宋宜臻.png' WHERE year = '2020' AND name = '好盒器';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2020_玉山銀行_台大創創logo-蕭存佑.png' WHERE year = '2020' AND name = '智慧看護媒合平台 Home心';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2020_商之器_傑精靈logo-Steven-Su.png' WHERE year = '2020' AND name = '即時非侵入性人臉辨識偵測心跳與呼吸技術 傑精靈';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2020_康寧_MUSK-logo-Ching-Wen-Huang.png' WHERE year = '2020' AND name = 'MUSK system MUSK Technology';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_logo-dwave-depng-Henry-Lin.png' WHERE year = '2020' AND name = '音樂語音相關AI技術 DeepWave';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_Cardbo_MaterialDesign_Pure2D-Ryan-Hu-1-1.png' WHERE year = '2020' AND name = '卡伯';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_SAT_Logo_776_386-2-Yu-Stephen-e1603360425770.png' WHERE year = '2020' AND name = 'SAT. Knowledge';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2020_聯經_GoodieLogo-Ramos-Chang-e1603360296695.png' WHERE year = '2020' AND name = 'Goodie APP';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_2021_台商資源國際_維爾歐德logo-werold-studio.png' WHERE year = '2020' AND name = 'AR虛擬世界平台 維爾歐德';
UPDATE historical_startups SET logo_local_path = '/historical/2020/13580_memorenceAI_logo-e1610694855990.png' WHERE year = '2020' AND name = 'Memorence AI 智能影像辨識系統';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_開吧_logo.jpg' WHERE year = '2021' AND name = '開吧餐飲顧問股份有限公司 開吧';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_coherence1-Cole-S.-Wu.png' WHERE year = '2021' AND name = 'Coherence Bio Coherence Bio';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_漸層灼灼中字-縱去背-Jocelyn-Chen.png' WHERE year = '2021' AND name = '灼灼科技 DLBox';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕快照-2021-09-22-下午4.06.30.png' WHERE year = '2021' AND name = 'InTOL: Intelligent Test Oracle Lab 穎鞱資訊股份有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕快照-2021-09-22-下午4.11.28.png' WHERE year = '2021' AND name = 'fish-ER 魚健康尾環ER與行為監測系統';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕快照-2021-09-22-下午4.06.20.png' WHERE year = '2021' AND name = '醫光生技團隊 FINE scope';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_takeawayla_logo-luk-wingsan.png' WHERE year = '2021' AND name = 'Takeawayla Takeawayla';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-15-164548.png' WHERE year = '2021' AND name = '男孩團隊 會員數位行銷數據分析';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_天公伯logo-Chris-Chen.jpg' WHERE year = '2021' AND name = '天公伯手路菜團隊 天公伯手路菜平台';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-15-163624.png' WHERE year = '2021' AND name = 'Keedle籽樂教育 智能化精準教育系統';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_fansee-logo-鄭富源.png' WHERE year = '2021' AND name = 'FANSEE 童畫童話';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_Dakodata_logo-Ching-Tien.png' WHERE year = '2021' AND name = 'DakoData Dako';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-15-161635.png' WHERE year = '2021' AND name = '智慧價值股份有限公司 AI投資戰情室';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_logo_bg1-YENCHEN-CHU.png' WHERE year = '2021' AND name = '揚揚創新科技 Ctrl A現場控-最佳OMO應用服務';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_logo-炸蝦軟軟.png' WHERE year = '2021' AND name = 'TeaClass查課 TeaClass查課';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_youuxi1024-Ariel-Lin.png' WHERE year = '2021' AND name = '翻篇Funnpen 翻篇智能導購';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_居家整聊室_生活職人平台_logo-Shina-Yang.png' WHERE year = '2021' AND name = '居家整聊室 生活職人媒合平台';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-15-161139.png' WHERE year = '2021' AND name = 'AIdea AIdea 人工智慧共創平台';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_爾科-LOGO-去背檔案-Ching-Chen.png' WHERE year = '2021' AND name = '爾科 ERRK 爾科智能健康助理';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-15-155757.png' WHERE year = '2021' AND name = '思惟睡眠科技股份有限公司 數據可驅動可複製睡眠中心(Data-Driven Scalable Sleep Labs, DSL®)';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_x_KOLABLElogo-徐愷.png' WHERE year = '2021' AND name = 'KOLABLE KOLABLE';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-15-153600.png' WHERE year = '2021' AND name = 'GOROX 3D全彩與多材質列印混鍊機';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_健康盟_LOGO標準字中英-王文利.png' WHERE year = '2021' AND name = '健康盟 DigiMed';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-15-154801.png' WHERE year = '2021' AND name = '醫淬思股份有限公司 醫療社群顧問與商轉平台';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_Holy-Bug_Logo-With-IP-蔡曜隆.png' WHERE year = '2021' AND name = 'HolyBug 遊戲卡牌鑑定與交易平台';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_Logo_1024-studio-slash.png' WHERE year = '2021' AND name = 'Slash studio C.C.S. 計畫';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_杯特.png' WHERE year = '2021' AND name = '杯特 uCup永續杯平台與AIoT感測創新清洗系統';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-15-121235.png' WHERE year = '2021' AND name = '安彼企業 中小企業成長平台';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_20200503-remoteNC-logo-vert-01-1-Beatrice-HU.png' WHERE year = '2021' AND name = 'RemoteNC RemoteNC 雲端加工專家系統';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_1629184964003-Aryan-Hong.jpg' WHERE year = '2021' AND name = '聚星聯網 聚星聯網方案';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-15-113817.png' WHERE year = '2021' AND name = '精拓生技 EVA Select';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-15-114321.png' WHERE year = '2021' AND name = 'NanoParma SeraParma COVID-19 IgM 快篩檢測試劑、AirParma 新冠奈米盾';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_PackAge-配客嘉股份有限公司-logo.png' WHERE year = '2021' AND name = '配客嘉股份有限公司 循環包裝服務體系';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-15-111742.png' WHERE year = '2021' AND name = 'AITM Molecular Pocket Doctor (Mo-Po-Doc)';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-15-112814.png' WHERE year = '2021' AND name = '孚創雲端股份有限公司 Patent Search, Patent Vault, Design Search, Due Diligence, Quality Insights, SEP OmniLytics';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_1629681395509-Alfred-Wu.png' WHERE year = '2021' AND name = 'AIPLUX LOFA';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_車庫_Crypto-Arsenal_logo-Li-Richard-1.png' WHERE year = '2021' AND name = 'Crypto-Arsenal Automated SaaS Crypto-Trading Platform';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-15-105154.png' WHERE year = '2021' AND name = 'thingnario Photon';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_freezone-logo-combination-01-Jason-Wang.png' WHERE year = '2021' AND name = 'FooSpace 自由食間';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_LAPSEE去背-許晴棻-Beverly.png' WHERE year = '2021' AND name = 'LAPSEE萊剖析 媒體素養教育教材、相關影片';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-15-103500.png' WHERE year = '2021' AND name = 'BioFlow 可移動式氣流阻隔手術裝置';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_pick-logo-吳佩軒.png' WHERE year = '2021' AND name = 'PICK （a cross-functional team from Blue Planet Inc.） PICK';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_鳴天設計logo-Zeal-Design.png' WHERE year = '2021' AND name = '鳴天設計 E-YES兒童弱視訓練器';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_TwentythreeLogo-T-Oscar.png' WHERE year = '2021' AND name = '二拾衫 二拾衫';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-14-172134.png' WHERE year = '2021' AND name = 'CyHorus CyHorus';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_Petit-logo-陳希涵.png' WHERE year = '2021' AND name = 'Petit小劇場 暑期戲劇營隊';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_Circle-by-Circle-Logo_1024x1024-Erin-Yang.png' WHERE year = '2021' AND name = 'Circle by Circle Circle by Circle';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_logo-b101105035-TMU.png' WHERE year = '2021' AND name = 'Spersor';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_高中生資訊網新logo-e1643006973432.png' WHERE year = '2021' AND name = 'EZ學習歷程 申請大學備審一站式製作平台';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-14-165751.png' WHERE year = '2021' AND name = 'EZ學習歷程 申請大學備審一站式製作平台';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕快照-2021-09-22-下午1.14.07.png' WHERE year = '2021' AND name = 'Workfe工作咖啡 咖啡廳即時資訊應用軟體';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-09-14-155308-2.png' WHERE year = '2021' AND name = 'PISTA Osprey';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_車庫_台大創創logo-Bryan-Lee.png' WHERE year = '2021' AND name = '賽神仙 Prediction in cancer patient by using big data approach';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021-02-24-2.png' WHERE year = '2021' AND name = 'Vetech Vetty';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_Screen-Shot-2021-02-09-at-10.32.52-PM-Wenyn-Wang.png' WHERE year = '2021' AND name = 'PeekurFinance PeekurFinance';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_玉山銀行_彼利數位資訊logo-chuan-yi.png' WHERE year = '2021' AND name = '彼利數位資訊股份有限公司 Wholive 誰住我家';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_螢幕擷取畫面-2021-02-24-143043.png' WHERE year = '2021' AND name = '歐姆佳科技（周錫增教授價創計畫） Ohm plus fast 5G毫米波快速校正系統';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021-02-24-6.png' WHERE year = '2021' AND name = 'Astron Medtech (TendMIN) Maxtend';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_台灣網格技術有限公司Meshub-Ka-Kin-Kevin-Wong.png' WHERE year = '2021' AND name = 'Meshub';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_談談科技股份有限公司_台大創創LOGO-Wang-Jennifer.png' WHERE year = '2021' AND name = 'ZIMA Inc.';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021-02-24-5.png' WHERE year = '2021' AND name = '陳宏銘教授科技部價創計畫擴增實境之光場眼鏡 Light Field AR Glasses';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021-02-24-4.png' WHERE year = '2021' AND name = 'UpperMed PD Care';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_WaCare-logo-5加7是Cheryl.png' WHERE year = '2021' AND name = 'LaVida Tec. WaCare遠距健康';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_加速器_hunger夯客logo-王嘉宏.png' WHERE year = '2021' AND name = 'hunger夯客';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_台大創創加速器_媽爹講故事logo-Avery-Hua.png' WHERE year = '2021' AND name = 'MOM&DAD 媽爹講故事';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_SiriuXense_Logo-01-Ruby-Hung.png' WHERE year = '2021' AND name = '澔心科技 胎兒暨嬰幼兒智能照護服務 Fetal & Infant Care System';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_EnterpriseLogo-Corner-Archer-Chiang.png' WHERE year = '2021' AND name = 'Giftpack';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_台大創創加速器_ApplatoLogo-Yen-Chen.png' WHERE year = '2021' AND name = 'Applato 智慧健康餐點推薦及飲食管理系統';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_pinacell01-b-Max-Chang.png' WHERE year = '2021' AND name = '綠冠農業有限公司 鳳梨葉衍伸產品';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021-02-24.png' WHERE year = '2021' AND name = 'ZERO BOTTLE 純淨洗髮露';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021-02-22-6.png' WHERE year = '2021' AND name = '凡立橙股份有限公司 ECOCO循環經濟';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_台商資源國際垂直加速器_茶茶團隊logo-茶茶.png' WHERE year = '2021' AND name = '茶茶團隊';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021-02-22-3.png' WHERE year = '2021' AND name = '捷思博科技, JetSparq Aimpfly，AI智造影像辨識平台';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021-02-22-2.png' WHERE year = '2021' AND name = 'Energy-Craft 異質訊號AIoT Gateway';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021-02-22.png' WHERE year = '2021' AND name = '汎思數據 AI 實務所: 數據工程服務';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_surreal-edu-logo-徐凡Joanna.png' WHERE year = '2021' AND name = '超現實科技 Surreal Education';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_親子天下_MangaChat_logo-Joe-Huang.png' WHERE year = '2021' AND name = 'MangaChat';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_親子天下_猿創力程式設計學校Logo-Kennan-Chen-1-1.png' WHERE year = '2021' AND name = '猿創力程式設計學校 猿創力K12程式素養數位學習系統／Discovery Education Coding數位教材';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_INSPOT-LOGO_工作區域-1-複本-2-Nick-Lee.png' WHERE year = '2021' AND name = 'super方 inspot IG熱搜';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_台商資源國際_維爾歐德logo-werold-studio.png' WHERE year = '2021' AND name = '維爾歐德 AR虛擬世界平台';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_台商垂直_穀米機工logo-郭人綺-1-1.png' WHERE year = '2021' AND name = '穀米機工 科技藝術與跨領域創意整合';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021-02-24-1.png' WHERE year = '2021' AND name = 'Amago Trip Amago B2B One-Stop Travel Platform';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2020_酷嗑博士_台大創創logo-庭瑜-e1611913131292.png' WHERE year = '2021' AND name = '酷嗑博士 Cooktor 酷嗑食驗室 Cooktor Lab';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2020_車庫_RosyFace春色-shao-en-Huang.png' WHERE year = '2021' AND name = 'Rosy Face 春色';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_Vitacies-Novotech_台大創創logo-Aniket-Limaye.png' WHERE year = '2021' AND name = 'Vitacies Novotech Protein metabolites and enzyme feed supplement';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_車庫_INPERSONlogo-蔡侑軒.jpg' WHERE year = '2021' AND name = 'INPERSON 年輕人的聚會社交平台';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2020_車庫孵化器_Foodeastlogo-李如寶.png' WHERE year = '2021' AND name = 'Foodeast 越食煮憶美食互動料理盒';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2020_車庫_LIMeat_logo-Dan-Zheng.png' WHERE year = '2021' AND name = 'LIMeat';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_台大車庫孵化器_直覺職掘logo-林潤千-1-1.png' WHERE year = '2021' AND name = '直覺職掘 給國中生的職業體驗營';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2021_台大車庫_FCS-Jung-Hsuan-Tsao-scaled-e1612158972147.jpg' WHERE year = '2021' AND name = 'FCS Ascelleia氣候智慧平台';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2020_車庫_好學問logo-Kevin-Liao.png' WHERE year = '2021' AND name = '好學.問 Q engine';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_2020_女性線上療癒助理與線下服務_窩聚．共好日常-Ansel-Yu-e1611929666676.png' WHERE year = '2021' AND name = '窩聚．共好日常 女性線上療癒助理與線下服務';
UPDATE historical_startups SET logo_local_path = '/historical/2021/13575_Kaik21-7-1.png' WHERE year = '2021' AND name = 'Kaik Teachify 開課快手';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_TechInvest科創投資.png' WHERE year = '2022' AND name = 'TechInvest科創投資 軟體架構顧問服務';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_MetaCool散熱專家.png' WHERE year = '2022' AND name = 'MetaCool散熱專家 超冷卻材料';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_綠活賦能.png' WHERE year = '2022' AND name = '綠活賦能 通用療癒花園';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_Topo-Logo-Square-翁肇陽.png' WHERE year = '2022' AND name = 'Creanity Topo';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_企桃囡仔.png' WHERE year = '2022' AND name = '企桃囡仔 跨域銀髮協作遊戲工作坊';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_STOPWET.png' WHERE year = '2022' AND name = 'STOPWET 新型態離子電泳導入止汗裝置';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_智泉智能LOGO-Shu-chiang-Chuang.png' WHERE year = '2022' AND name = '智泉智能 影像識別AI系統與應用';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_銅板資本家.png' WHERE year = '2022' AND name = '銅板資本家 給青少年的投資理財課';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_說說實驗室.png' WHERE year = '2022' AND name = '說說實驗室';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_DonaeLabs-logo_1-Pau-Pernghwa-Kung.jpg' WHERE year = '2022' AND name = 'DonaeLabs Netscope';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_POSTORY-BIS-Log-1024px_2-Hank-Chou.png' WHERE year = '2022' AND name = '溫度寄股份有限公司 POSTORY';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_Tricuss.io_.png' WHERE year = '2022' AND name = 'Tricuss.io 教育與知識交流的 Slack';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_interWellness-Long-Logo-Transparent-林芳如.png' WHERE year = '2022' AND name = 'interWellness為你而思 interWellness為你而思飲食友善平臺';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_TeraThinker.png' WHERE year = '2022' AND name = 'Tera Thinker 人工智慧自適應學習系統';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_VoiceTube.png' WHERE year = '2022' AND name = 'VoiceTube Name';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_Qbi塊樂方程式.png' WHERE year = '2022' AND name = 'Qbi塊樂方程式 Name';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_JOYSHOT.png' WHERE year = '2022' AND name = '旅攝數位股份有限公司 JOYSHOT';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_樂易創.png' WHERE year = '2022' AND name = '樂易創 樂點APP-最簡單的歌曲創作工具';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_杯特.png' WHERE year = '2022' AND name = '杯特 uCup永續杯平台';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_REcarbon-e1647412167890.jpeg' WHERE year = '2022' AND name = 'REcarbon 企業碳中和平台';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_螢幕快照-2022-03-16-下午3.41.59.png' WHERE year = '2022' AND name = 'Encore 安可日子';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_超現實科技.png' WHERE year = '2022' AND name = '超現實科技 SURREALM遠距共學平台';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_INVENTAILOGO_工作區域-1-.png' WHERE year = '2022' AND name = 'InventAI DeepFlow & DeepVoice';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_RealT4.png' WHERE year = '2022' AND name = 'RealT4 Talentrue';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_Logo_1024-studio-slash.png' WHERE year = '2022' AND name = 'Slash studio 循環設計服務Slash studio';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_傑精靈.png' WHERE year = '2022' AND name = '傑精靈 FaCare';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_醫淬思股份有限公司.png' WHERE year = '2022' AND name = '醫淬思股份有限公司 值得信賴的O2O醫療健康嚴選平台';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_WaCare-村銘陳.png' WHERE year = '2022' AND name = '吉樂健康資訊科技股份有限公司 WaCare遠距健康';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_愛米菜去背logo-彭禹庭.png' WHERE year = '2022' AND name = '愛米菜 愛米菜餐廳';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_楽坡bonbox.png' WHERE year = '2022' AND name = '樂邁喬國際股份有限公司 楽坡bonbox';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_The-Compass.png' WHERE year = '2022' AND name = 'The Compass Comfytube';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_New-Biodesign.png' WHERE year = '2022' AND name = 'New Biodesign Eternal tube';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_Medevice.png' WHERE year = '2022' AND name = 'Medevice 磁力防導絲滯留裝置';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_MeTCare.jpg' WHERE year = '2022' AND name = 'MeTCare Home-based IOP measuring device';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_電子藥瓶.png' WHERE year = '2022' AND name = '電子藥瓶';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_南瓜虛擬科技.png' WHERE year = '2022' AND name = '南瓜虛擬科技 Name';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_Speed-3D-Inc..png' WHERE year = '2022' AND name = 'Speed 3D Inc. Picbot－AR智慧拍照機器人 / FunkAR－WebAR送禮平台';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_Fun2_Logo_300dpi_1024x1024px_A-Sophia-Huang.png' WHERE year = '2022' AND name = '方兔互動娛樂工作室 台北大空襲';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_米菲多媒體logo-04-Aileen-MIFLY.png' WHERE year = '2022' AND name = 'MIFLY MAKAR';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_MAI_Logo-01-Sam-Jang.png' WHERE year = '2022' AND name = 'MAI BodyMap';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_104_corma-Ray-Lee.png' WHERE year = '2022' AND name = '科碼新媒體 AR遠距商務系統';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_全球動力科技股份有限公司.png' WHERE year = '2022' AND name = '全球動力科技股份有限公司 元宇宙警察訓練、元宇宙軍事訓練、元宇宙智慧交通、元宇宙智慧安全';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_拿拿科技行銷logo去背-Jimmy-Yiu-1.png' WHERE year = '2022' AND name = 'take!智慧體驗行銷 拿拿科技行銷';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_悠揚團隊LOGO.jpg' WHERE year = '2022' AND name = '心偵環 悠揚團隊';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_大話中文LOGO.png' WHERE year = '2022' AND name = '大話中文內容平台與華人文化線上課程 大話中文';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_酷堤康科技logo去背-Tiffany-Hsiao.png' WHERE year = '2022' AND name = 'SMARTAX 365 Ecosystem 酷堤康科技';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_VISIONER-梁妙華.png' WHERE year = '2022' AND name = '超解析微型光達系統 Visioner幻視科技';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_XPACE-logo去背-Astrid-CH.png' WHERE year = '2022' AND name = 'X-CITY XPACE';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_Meta-Arte-D-1-3-white-Headquarters-MetaArche.png' WHERE year = '2022' AND name = 'ARCHE Studio META ARCHE Technology';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_OhBot-LOGO.png' WHERE year = '2022' AND name = 'Oh!Bot Line SCRM Oh!Bot';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_LuminX-LOGO-Vincent-Fan.png' WHERE year = '2022' AND name = 'LuminX Tracking Kit 路明思生技';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_聲鮮時采Logo去背-王薇瑄.jpg' WHERE year = '2022' AND name = '聲音內容(Podcast、有聲書) 聲鮮時采科技';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_飛天奶茶logo去背-飛天奶茶Flying-Milk-Tea.jpg' WHERE year = '2022' AND name = '飛天奶茶';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_樂多科技LOGO去背-Tonton-Yang.jpg' WHERE year = '2022' AND name = 'Uni-Trip 樂多科技';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_RENEAL-logo去背-Neal-tseng.png' WHERE year = '2022' AND name = 'RENEAL';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_logo-Peter-Yeh.png' WHERE year = '2022' AND name = 'Pesto Green Super App Pesto Green';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_Jmem-tek.jpg' WHERE year = '2022' AND name = 'Duet OTP Jmem tek';
UPDATE historical_startups SET logo_local_path = '/historical/2022/13379_Artifact智器科技.png' WHERE year = '2022' AND name = 'LPG物聯網雲端平台 Artifact智器科技';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_撩慾logo_new.png' WHERE year = '2023' AND name = '撩慾';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_NFTicketing_logo去背-Tseng-Wilson.png' WHERE year = '2023' AND name = 'NFTicketing';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_人木有限公司logo去背-Evelyn-Chou.png' WHERE year = '2023' AND name = '人木有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_俞松良.jpg' WHERE year = '2023' AND name = '台大俞松良老師團隊';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_厝邊MyNeighbor-logo去背-Chinchin-Yang.png' WHERE year = '2023' AND name = '厝邊MyNeighbor';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_恩食logo去背-chen小琪.jpg' WHERE year = '2023' AND name = '恩食';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_起起夫夫logo去背-許博超.png' WHERE year = '2023' AND name = '起起夫夫';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_賦語科技logo去背-Answer-Corp.png' WHERE year = '2023' AND name = '賦語科技 Answer Corp.';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_繁晶科技logo去背-Wang-Mike.png' WHERE year = '2023' AND name = '繁晶科技 Ranictek';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_BadX-logo去背-YU-HAO-FAN.png' WHERE year = '2023' AND name = 'FozirTex 賦喆運動科技';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_Combogic-Tech-櫛構科技logo去背-Wei-Ming-Li.png' WHERE year = '2023' AND name = 'Combogic Tech. 櫛構科技';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_cooseii-15-Mark-Yeh.png' WHERE year = '2023' AND name = '點點善cooseii';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_havppen_logo_正方形黑-2-ALLISON-CHIU.png' WHERE year = '2023' AND name = '哈彼科技股份有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_Logo_Final-胡兆棨.png' WHERE year = '2023' AND name = '科學毛怪 PetSci';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_0418-logo外框.jpg' WHERE year = '2023' AND name = 'pergolas';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_Social-Monster社社發抖logo去背-孟芹.png' WHERE year = '2023' AND name = 'Social Monster社社發抖';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_UFO_Pay_logo去背-Arctic-Yen.png' WHERE year = '2023' AND name = 'UFO Pay 優付';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_Gocochain-logo去背-簡宜信.png' WHERE year = '2023' AND name = 'Gocochain';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_YE_LOGO去背-周庭宇.png' WHERE year = '2023' AND name = 'Y&E';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_奉茶行動logo去背-黃暐程_奉茶行動.png' WHERE year = '2023' AND name = '奉茶行動 My Hong-Te';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_DMKTZ-logo-Jac-Hsieh.jpg' WHERE year = '2023' AND name = 'DMKTZ Inc.';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_goldfinch_logo-Po-Han-Chung.png' WHERE year = '2023' AND name = 'Goldfinch';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_Linggle-邹丞勛.png' WHERE year = '2023' AND name = 'Linggle';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_Logo-Dark-Blue-1-PeiYing-Wu.png' WHERE year = '2023' AND name = '翱翔智慧股份有限公司 Owlsome Tech';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_Logo_Name-NH-Wang-Came1us.png' WHERE year = '2023' AND name = 'Tricuss';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_saltlab-logo去背-SaltLab.png' WHERE year = '2023' AND name = 'SaltLab';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_Trainge-logo去背-紀維綱Karl-Chi.png' WHERE year = '2023' AND name = 'Trainge';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_愛吠的狗娛樂股份有限公司LOGO去背-CHE.png' WHERE year = '2023' AND name = '愛吠的狗娛樂股份有限公司';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_logo_1024-Assign-Arch.png' WHERE year = '2023' AND name = 'Virsody';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_解放生活-logo-去背-Ben-Chen.png' WHERE year = '2023' AND name = 'Tracle 垃可';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_ZEMO-Logo-白底-呂學儒.png' WHERE year = '2023' AND name = 'ZEMO';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_5CBE3EA5-3B1E-46EA-9210-2F7EC008CBA4-alis507501.gif' WHERE year = '2023' AND name = '錨點影音';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_維爾歐德logo去背-werold-studio.png' WHERE year = '2023' AND name = '維爾歐德';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_104_corma-Ray-Lee.png' WHERE year = '2023' AND name = '科碼新媒體';
UPDATE historical_startups SET logo_local_path = '/historical/2023/13751_超現實科技logo-Lee-Ting.png' WHERE year = '2023' AND name = '超現實科技';

-- mentors.photo_url  (backfill via name hint match, 122 candidates)
UPDATE mentors SET photo_url = '/mentors/wp/3011.jpg' WHERE photo_url IS NULL AND name LIKE '%東方線上%';
UPDATE mentors SET photo_url = '/mentors/wp/3012.jpg' WHERE photo_url IS NULL AND name LIKE '%富盈數據%';
UPDATE mentors SET photo_url = '/mentors/wp/3144.jpg' WHERE photo_url IS NULL AND name LIKE '%任麗玲%';
UPDATE mentors SET photo_url = '/mentors/wp/3145.jpg' WHERE photo_url IS NULL AND name LIKE '%江進元%';
UPDATE mentors SET photo_url = '/mentors/wp/3146.jpg' WHERE photo_url IS NULL AND name LIKE '%吳昇奇%';
UPDATE mentors SET photo_url = '/mentors/wp/3147.jpg' WHERE photo_url IS NULL AND name LIKE '%李吉仁%';
UPDATE mentors SET photo_url = '/mentors/wp/3149.jpg' WHERE photo_url IS NULL AND name LIKE '%范炘%';
UPDATE mentors SET photo_url = '/mentors/wp/3150.jpg' WHERE photo_url IS NULL AND name LIKE '%張佳欽%';
UPDATE mentors SET photo_url = '/mentors/wp/3151.jpg' WHERE photo_url IS NULL AND name LIKE '%郭家齊%';
UPDATE mentors SET photo_url = '/mentors/wp/3152.jpg' WHERE photo_url IS NULL AND name LIKE '%陳一強%';
UPDATE mentors SET photo_url = '/mentors/wp/3153.jpg' WHERE photo_url IS NULL AND name LIKE '%陳百州%';
UPDATE mentors SET photo_url = '/mentors/wp/3154.jpg' WHERE photo_url IS NULL AND name LIKE '%陳克錡%';
UPDATE mentors SET photo_url = '/mentors/wp/3155.jpg' WHERE photo_url IS NULL AND name LIKE '%陳識仁%';
UPDATE mentors SET photo_url = '/mentors/wp/3156.jpg' WHERE photo_url IS NULL AND name LIKE '%陳顯立%';
UPDATE mentors SET photo_url = '/mentors/wp/3157.jpg' WHERE photo_url IS NULL AND name LIKE '%曾正忠%';
UPDATE mentors SET photo_url = '/mentors/wp/3158.jpg' WHERE photo_url IS NULL AND name LIKE '%黃世貝%';
UPDATE mentors SET photo_url = '/mentors/wp/3159.jpg' WHERE photo_url IS NULL AND name LIKE '%黃怡佳%';
UPDATE mentors SET photo_url = '/mentors/wp/3161.jpg' WHERE photo_url IS NULL AND name LIKE '%楊志偉%';
UPDATE mentors SET photo_url = '/mentors/wp/3162.jpg' WHERE photo_url IS NULL AND name LIKE '%詹益鑑%IC%';
UPDATE mentors SET photo_url = '/mentors/wp/3163.jpg' WHERE photo_url IS NULL AND name LIKE '%劉政惠%';
UPDATE mentors SET photo_url = '/mentors/wp/3164.jpg' WHERE photo_url IS NULL AND name LIKE '%盧人瑞%';
UPDATE mentors SET photo_url = '/mentors/wp/3165.jpg' WHERE photo_url IS NULL AND name LIKE '%瞿志豪%';
UPDATE mentors SET photo_url = '/mentors/wp/3167.jpg' WHERE photo_url IS NULL AND name LIKE '%洪小玲2%';
UPDATE mentors SET photo_url = '/mentors/wp/3168.jpg' WHERE photo_url IS NULL AND name LIKE '%黃逸甫2%';
UPDATE mentors SET photo_url = '/mentors/wp/3169.jpg' WHERE photo_url IS NULL AND name LIKE '%王俞又2%';
UPDATE mentors SET photo_url = '/mentors/wp/3399.jpg' WHERE photo_url IS NULL AND name LIKE '%張益肇＿台大創創加速器%';
UPDATE mentors SET photo_url = '/mentors/wp/3400.png' WHERE photo_url IS NULL AND name LIKE '%TEC%08_William%Pan%盤龍%台大創創加速器%';
UPDATE mentors SET photo_url = '/mentors/wp/3403.jpeg' WHERE photo_url IS NULL AND name LIKE '%華國媛%';
UPDATE mentors SET photo_url = '/mentors/wp/3404.jpg' WHERE photo_url IS NULL AND name LIKE '%楊少夫%';
UPDATE mentors SET photo_url = '/mentors/wp/3928.jpg' WHERE photo_url IS NULL AND name LIKE '%張安佐%';
UPDATE mentors SET photo_url = '/mentors/wp/3990.jpg' WHERE photo_url IS NULL AND name LIKE '%郭瑞祥_2%';
UPDATE mentors SET photo_url = '/mentors/wp/3999.jpg' WHERE photo_url IS NULL AND name LIKE '%金麗英%Joset%King%';
UPDATE mentors SET photo_url = '/mentors/wp/4009.jpg' WHERE photo_url IS NULL AND name LIKE '%陳宏益%Hongyi%Chen%';
UPDATE mentors SET photo_url = '/mentors/wp/4012.jpg' WHERE photo_url IS NULL AND name LIKE '%陳怡光（陳爸）%';
UPDATE mentors SET photo_url = '/mentors/wp/4019.jpg' WHERE photo_url IS NULL AND name LIKE '%蔡明順%';
UPDATE mentors SET photo_url = '/mentors/wp/4024.png' WHERE photo_url IS NULL AND name LIKE '%陶韻智%Sting%Tao%';
UPDATE mentors SET photo_url = '/mentors/wp/4026.png' WHERE photo_url IS NULL AND name LIKE '%郭大經%';
UPDATE mentors SET photo_url = '/mentors/wp/4062.jpg' WHERE photo_url IS NULL AND name LIKE '%駱國綸KL%';
UPDATE mentors SET photo_url = '/mentors/wp/4064.jpg' WHERE photo_url IS NULL AND name LIKE '%孫治華%ZH%Sun%';
UPDATE mentors SET photo_url = '/mentors/wp/4070.png' WHERE photo_url IS NULL AND name LIKE '%Howard%Chang%';
UPDATE mentors SET photo_url = '/mentors/wp/4093.png' WHERE photo_url IS NULL AND name LIKE '%張鴻文%Howard%Chang%';
UPDATE mentors SET photo_url = '/mentors/wp/4096.jpg' WHERE photo_url IS NULL AND name LIKE '%曾正忠%Vincent%';
UPDATE mentors SET photo_url = '/mentors/wp/4242.jpg' WHERE photo_url IS NULL AND name LIKE '%TSS_3930%-%林嘉瑜%';
UPDATE mentors SET photo_url = '/mentors/wp/4243.jpg' WHERE photo_url IS NULL AND name LIKE '%羅子亮%Robert%Lo%';
UPDATE mentors SET photo_url = '/mentors/wp/4245.jpeg' WHERE photo_url IS NULL AND name LIKE '%楊家彥%Steven%Yang%';
UPDATE mentors SET photo_url = '/mentors/wp/4247.png' WHERE photo_url IS NULL AND name LIKE '%螢幕快照%2020-04-23%下午5.20.46%';
UPDATE mentors SET photo_url = '/mentors/wp/4251.jpg' WHERE photo_url IS NULL AND name LIKE '%94420094_307744350275650_5692361620450181120_n%';
UPDATE mentors SET photo_url = '/mentors/wp/4252.jpg' WHERE photo_url IS NULL AND name LIKE '%曾正忠%Vincent%';
UPDATE mentors SET photo_url = '/mentors/wp/4273.png' WHERE photo_url IS NULL AND name LIKE '%簡榮宗%Alan%Chien%';
UPDATE mentors SET photo_url = '/mentors/wp/4284.jpg' WHERE photo_url IS NULL AND name LIKE '%林家振%Jonathan%Lin%';
UPDATE mentors SET photo_url = '/mentors/wp/4286.png' WHERE photo_url IS NULL AND name LIKE '%林家振%Jonathan%Lin%';
UPDATE mentors SET photo_url = '/mentors/wp/4290.png' WHERE photo_url IS NULL AND name LIKE '%螢幕快照%2020-05-29%下午5.36.15%';
UPDATE mentors SET photo_url = '/mentors/wp/4294.png' WHERE photo_url IS NULL AND name LIKE '%林家振%Jonathan%Lin%';
UPDATE mentors SET photo_url = '/mentors/wp/4306.jpeg' WHERE photo_url IS NULL AND name LIKE '%陳之逵%Allen%Chen%';
UPDATE mentors SET photo_url = '/mentors/wp/4330.jpg' WHERE photo_url IS NULL AND name LIKE '%蔡恩全%Davis%Tsai%';
UPDATE mentors SET photo_url = '/mentors/wp/4421.jpg' WHERE photo_url IS NULL AND name LIKE '%Jerry%Chen%';
UPDATE mentors SET photo_url = '/mentors/wp/4465.jpeg' WHERE photo_url IS NULL AND name LIKE '%黃沛聲%Bryan%';
UPDATE mentors SET photo_url = '/mentors/wp/4561.jpg' WHERE photo_url IS NULL AND name LIKE '%蘇欽豐%CF%Su%';
UPDATE mentors SET photo_url = '/mentors/wp/4566.jpg' WHERE photo_url IS NULL AND name LIKE '%曾正忠%Vincent%';
UPDATE mentors SET photo_url = '/mentors/wp/4668.jpg' WHERE photo_url IS NULL AND name LIKE '%DWAYNE%SYE%';
UPDATE mentors SET photo_url = '/mentors/wp/6158.png' WHERE photo_url IS NULL AND name LIKE '%陳仲竹%CC%Chen%';
UPDATE mentors SET photo_url = '/mentors/wp/6200.jpg' WHERE photo_url IS NULL AND name LIKE '%王馥蓓%Fupei%Wang%';
UPDATE mentors SET photo_url = '/mentors/wp/6285.jpg' WHERE photo_url IS NULL AND name LIKE '%連祥一%Sean%Lien%';
UPDATE mentors SET photo_url = '/mentors/wp/6288.png' WHERE photo_url IS NULL AND name LIKE '%梁幸堯%Michael%Hsin-Yao%Liang%';
UPDATE mentors SET photo_url = '/mentors/wp/6296.png' WHERE photo_url IS NULL AND name LIKE '%梁幸堯%Michael%Hsin-Yao%Liang%';
UPDATE mentors SET photo_url = '/mentors/wp/6298.png' WHERE photo_url IS NULL AND name LIKE '%梁幸堯%Michael%Hsin-Yao%Liang%';
UPDATE mentors SET photo_url = '/mentors/wp/6309.jpeg' WHERE photo_url IS NULL AND name LIKE '%梁幸堯%Michael%Hsin-Yao%Liang%';
UPDATE mentors SET photo_url = '/mentors/wp/6332.jpg' WHERE photo_url IS NULL AND name LIKE '%黃彗真%Jane%Huang%';
UPDATE mentors SET photo_url = '/mentors/wp/6337.jpg' WHERE photo_url IS NULL AND name LIKE '%Joyce%Lee%李如虹%';
UPDATE mentors SET photo_url = '/mentors/wp/6416.jpg' WHERE photo_url IS NULL AND name LIKE '%洪福利%Felix%Hong%';
UPDATE mentors SET photo_url = '/mentors/wp/6573.jpg' WHERE photo_url IS NULL AND name LIKE '%AQ9A5685%';
UPDATE mentors SET photo_url = '/mentors/wp/6689.png' WHERE photo_url IS NULL AND name LIKE '%王同年%Tony%Wang%';
UPDATE mentors SET photo_url = '/mentors/wp/6691.png' WHERE photo_url IS NULL AND name LIKE '%王同年%Tony%Wang_2%';
UPDATE mentors SET photo_url = '/mentors/wp/6693.png' WHERE photo_url IS NULL AND name LIKE '%王同年%Tony%Wang_3%';
UPDATE mentors SET photo_url = '/mentors/wp/6728.jpg' WHERE photo_url IS NULL AND name LIKE '%羅台青%Josephine%Lo%';
UPDATE mentors SET photo_url = '/mentors/wp/6736.jpg' WHERE photo_url IS NULL AND name LIKE '%曾正忠%Vincent_業師陣容%';
UPDATE mentors SET photo_url = '/mentors/wp/6949.jpg' WHERE photo_url IS NULL AND name LIKE '%劉永信%Spencer%Liu%';
UPDATE mentors SET photo_url = '/mentors/wp/7822.jpg' WHERE photo_url IS NULL AND name LIKE '%謝忠高%Peter%Hsieh%';
UPDATE mentors SET photo_url = '/mentors/wp/7893.jpg' WHERE photo_url IS NULL AND name LIKE '%陳琚安%Joann%Chen%';
UPDATE mentors SET photo_url = '/mentors/wp/9334.jpg' WHERE photo_url IS NULL AND name LIKE '%楊光磊Konrad%Young%';
UPDATE mentors SET photo_url = '/mentors/wp/9441.jpg' WHERE photo_url IS NULL AND name LIKE '%TEC%05_Thomas%Fann%';
UPDATE mentors SET photo_url = '/mentors/wp/9442.jpg' WHERE photo_url IS NULL AND name LIKE '%t_06%';
UPDATE mentors SET photo_url = '/mentors/wp/9443.jpg' WHERE photo_url IS NULL AND name LIKE '%金麗英.png%';
UPDATE mentors SET photo_url = '/mentors/wp/10303.jpg' WHERE photo_url IS NULL AND name LIKE '%Huang%Lee%NTUTEC%';
UPDATE mentors SET photo_url = '/mentors/wp/14953.jpeg' WHERE photo_url IS NULL AND name LIKE '%KQZf3g2a%';
UPDATE mentors SET photo_url = '/mentors/wp/14954.jpeg' WHERE photo_url IS NULL AND name LIKE '%KQZf3g2a%';
UPDATE mentors SET photo_url = '/mentors/wp/14961.jpg' WHERE photo_url IS NULL AND name LIKE '%91APP創辦人暨董事長%何英圻%';
UPDATE mentors SET photo_url = '/mentors/wp/15277.jpg' WHERE photo_url IS NULL AND name LIKE '%IMG_0010%';
UPDATE mentors SET photo_url = '/mentors/wp/15597.jpeg' WHERE photo_url IS NULL AND name LIKE '%綠藤生機共同創辦人暨執行長_鄭涵睿%Harris%';
UPDATE mentors SET photo_url = '/mentors/wp/15600.jpeg' WHERE photo_url IS NULL AND name LIKE '%綠藤生機共同創辦人暨執行長_鄭涵睿%Harris%';
UPDATE mentors SET photo_url = '/mentors/wp/15694.jpeg' WHERE photo_url IS NULL AND name LIKE '%天下學習(Jim-2)-2022%';
UPDATE mentors SET photo_url = '/mentors/wp/15696.jpeg' WHERE photo_url IS NULL AND name LIKE '%IMG_1063%';
UPDATE mentors SET photo_url = '/mentors/wp/17117.jpg' WHERE photo_url IS NULL AND name LIKE '%_Z720184%';
UPDATE mentors SET photo_url = '/mentors/wp/17125.png' WHERE photo_url IS NULL AND name LIKE '%Yiju%Chen_Photo%';
UPDATE mentors SET photo_url = '/mentors/wp/17134.jpg' WHERE photo_url IS NULL AND name LIKE '%Carrie%Tsai_05%';
UPDATE mentors SET photo_url = '/mentors/wp/17384.jpg' WHERE photo_url IS NULL AND name LIKE '%PHILIPS-3021v2%';
UPDATE mentors SET photo_url = '/mentors/wp/17390.jpg' WHERE photo_url IS NULL AND name LIKE '%導師個人照片%';
UPDATE mentors SET photo_url = '/mentors/wp/17740.jpg' WHERE photo_url IS NULL AND name LIKE '%王琍瑩照片%(台大創創中心)%';
UPDATE mentors SET photo_url = '/mentors/wp/17935.jpg' WHERE photo_url IS NULL AND name LIKE '%unnamed%';
UPDATE mentors SET photo_url = '/mentors/wp/18507.jpg' WHERE photo_url IS NULL AND name LIKE '%林文欽7M大檔案公關肖像照片%';
UPDATE mentors SET photo_url = '/mentors/wp/18713.png' WHERE photo_url IS NULL AND name LIKE '%個人獨照-鍾哲民%';
UPDATE mentors SET photo_url = '/mentors/wp/18816.jpeg' WHERE photo_url IS NULL AND name LIKE '%Adms%個人照%方形%';
UPDATE mentors SET photo_url = '/mentors/wp/18986.jpeg' WHERE photo_url IS NULL AND name LIKE '%DSC_5619-KL-Loh-林嘉瑜-scaled-e1583304342182-150x150%';
UPDATE mentors SET photo_url = '/mentors/wp/18987.png' WHERE photo_url IS NULL AND name LIKE '%簡榮宗%';
UPDATE mentors SET photo_url = '/mentors/wp/18988.png' WHERE photo_url IS NULL AND name LIKE '%楊家彥%';
UPDATE mentors SET photo_url = '/mentors/wp/18989.jpeg' WHERE photo_url IS NULL AND name LIKE '%劉永信%Spencer%Liu%';
UPDATE mentors SET photo_url = '/mentors/wp/18990.jpeg' WHERE photo_url IS NULL AND name LIKE '%吳昇奇%Gary%';
UPDATE mentors SET photo_url = '/mentors/wp/18991.png' WHERE photo_url IS NULL AND name LIKE '%Janice_11%';
UPDATE mentors SET photo_url = '/mentors/wp/18992.jpg' WHERE photo_url IS NULL AND name LIKE '%未命名設計%';
UPDATE mentors SET photo_url = '/mentors/wp/18993.jpg' WHERE photo_url IS NULL AND name LIKE '%未命名設計%(2)%';
UPDATE mentors SET photo_url = '/mentors/wp/18994.png' WHERE photo_url IS NULL AND name LIKE '%個人照%';
UPDATE mentors SET photo_url = '/mentors/wp/18995.jpeg' WHERE photo_url IS NULL AND name LIKE '%DSC_5619-KL-Loh-林嘉瑜-scaled-e1583304342182%';
UPDATE mentors SET photo_url = '/mentors/wp/18996.png' WHERE photo_url IS NULL AND name LIKE '%螢幕快照-2020-04-23-下午5.20.46%';
UPDATE mentors SET photo_url = '/mentors/wp/18997.jpeg' WHERE photo_url IS NULL AND name LIKE '%個人照_400x400%';
UPDATE mentors SET photo_url = '/mentors/wp/18998.jpeg' WHERE photo_url IS NULL AND name LIKE '%吳昇奇%';
UPDATE mentors SET photo_url = '/mentors/wp/19000.jpg' WHERE photo_url IS NULL AND name LIKE '%未命名設計%(2)%';
UPDATE mentors SET photo_url = '/mentors/wp/19057.jpeg' WHERE photo_url IS NULL AND name LIKE '%Izero--photo拷貝%';
UPDATE mentors SET photo_url = '/mentors/wp/19059.png' WHERE photo_url IS NULL AND name LIKE '%未命名設計%';
UPDATE mentors SET photo_url = '/mentors/wp/19350.jpeg' WHERE photo_url IS NULL AND name LIKE '%IMG_8295%(1)%';
UPDATE mentors SET photo_url = '/mentors/wp/19352.png' WHERE photo_url IS NULL AND name LIKE '%2%';
UPDATE mentors SET photo_url = '/mentors/wp/20036.jpg' WHERE photo_url IS NULL AND name LIKE '%c27ae6c2-1cbd-4791-8128-c001022a959e%';
UPDATE mentors SET photo_url = '/mentors/wp/20489.jpg' WHERE photo_url IS NULL AND name LIKE '%7M大檔案公關肖像照片-scaled-e1699860613618%';

COMMIT;

-- Verify:
-- SELECT year, COUNT(*) FILTER (WHERE logo_local_path IS NOT NULL) AS with_local,
--        COUNT(*) AS total
-- FROM historical_startups GROUP BY year ORDER BY year;

-- SELECT COUNT(*) FILTER (WHERE photo_url LIKE '/mentors/%') AS with_local FROM mentors;
